arch: bootstrap fixups

diff --git a/installer/arch/bootstrap b/installer/arch/bootstrap
--- a/installer/arch/bootstrap
+++ b/installer/arch/bootstrap
@@ -22,9 +22,6 @@ fi
 # - bash provides sh
 # - gawk provides awk
 PACKAGES_BOOTSTRAP="bash gawk pacman grep util-linux"
-# Packages we do not want to install (even if they are dependencies)
-# FIXME: This is probably a bad idea
-PACKAGES_BOOTSTRAP_IGNORE=""
 
 LIST="$tmp/list"
 FETCHDIRDB="$tmp/db"
@@ -57,8 +54,8 @@ echo "Fetching repository packages list..." 1>&2
 # Fetch Arch package database
 for REPO in $REPOS; do
     echo "Fetching $REPO..." 1>&2
-    MIRRORBASE="`echo $MIRROR | sed -e "s/\\$repo/$REPO/" \
-                                    -e "s/\\$arch/$ARCH/"`"
+    MIRRORBASE="`echo "$MIRROR" | sed -e "s/\\$repo/$REPO/" \
+                                      -e "s/\\$arch/$ARCH/"`"
     curlretry -o "$FETCHDIRDB/$REPO.db" "$MIRRORBASE/$REPO.db" 1>&2
     # Create package list in this format: $REPO:package-version
     tar tf "$FETCHDIRDB/$REPO.db" \
@@ -77,7 +74,6 @@ getdbfield() {
         m { print }
         /^%'"$FIELD"'%$/ { m = 1 }
     '
-    return 0
 }
 
 echo "Downloading and extracting packages..." 1>&2
@@ -96,44 +92,46 @@ while [ -n "$missing" ]; do
     for PACKAGE in $missing; do
         inst='y'
         # Do not install if already installed, or in ignore list
-        for IPKG in $installed $PACKAGES_BOOTSTRAP_IGNORE; do
+        for IPKG in $installed; do
             if [ "$IPKG" = "$PACKAGE" ]; then
                 inst='n'
                 break
             fi
         done
 
-        if [ "$inst" = 'y' ]; then
-            echo "Downloading and installing $PACKAGE..." 1>&2
-            PKG="`grep ":$PACKAGE-[0-9]" "$LIST" | head -n 1`"
-            if [ -z "$PKG" ]; then
-                echo "Cannot find package $PACKAGE..." 1>&2
-                exit 1
-            fi
-            REPO="`echo $PKG | cut -f 1 -d:`"
-            PKGVER="`echo $PKG | cut -f 2 -d:`"
-            FILE="`getdbfield "$REPO" "$PKGVER" "desc" "FILENAME"`"
-            MIRRORBASE="`echo $MIRROR | sed -e "s/\\$repo/$REPO/" \
-                                            -e "s/\\$arch/$ARCH/"`"
-            curlretry -o "$FETCHDIRPKG/$FILE" "$MIRRORBASE/$FILE" 1>&2
-            tar --warning=no-unknown-keyword -xkf "$FETCHDIRPKG/$FILE" \
-                --exclude ".PKGINFO" --exclude ".MTREE" \
-                --exclude ".INSTALL" --exclude ".Changelog" \
-                -C "$BOOTSTRAPCHROOT"
+        if [ "$inst" = 'n' ]; then
+            break
+        fi
 
-            # Get list of dependencies (ignore versions)
-            ndep="`getdbfield "$REPO" "$PKGVER" "depends" "DEPENDS" \
+        echo "Downloading and installing $PACKAGE..." 1>&2
+        PKG="`grep ":$PACKAGE-[0-9]" "$LIST" | head -n 1`"
+        if [ -z "$PKG" ]; then
+            echo "Cannot find package $PACKAGE..." 1>&2
+            exit 1
+        fi
+        REPO="`echo "$PKG" | cut -f 1 -d:`"
+        PKGVER="`echo "$PKG" | cut -f 2 -d:`"
+        FILE="`getdbfield "$REPO" "$PKGVER" "desc" "FILENAME"`"
+        MIRRORBASE="`echo "$MIRROR" | sed -e "s/\\$repo/$REPO/" \
+                                          -e "s/\\$arch/$ARCH/"`"
+        curlretry -o "$FETCHDIRPKG/$FILE" "$MIRRORBASE/$FILE" 1>&2
+        tar --warning=no-unknown-keyword -xkf "$FETCHDIRPKG/$FILE" \
+            --exclude ".PKGINFO" --exclude ".MTREE" \
+            --exclude ".INSTALL" --exclude ".Changelog" \
+            -C "$BOOTSTRAPCHROOT"
+
+        # Get list of dependencies (ignore versions)
+        ndep="`getdbfield "$REPO" "$PKGVER" "depends" "DEPENDS" \
                      | sed -n -e 's/^\([^<>=]*\).*$/\1/p' | tr '\n' ' '`"
 
-            # Some packages provide virtual packages (e.g. bash provides sh):
-            # Add those to the installed list
-            nprovides="`getdbfield "$REPO" "$PKGVER" "depends" "PROVIDES" \
+        # Some packages provide virtual packages (e.g. bash provides sh):
+        # Add those to the installed list
+        nprovides="`getdbfield "$REPO" "$PKGVER" "depends" "PROVIDES" \
                           | tr '\n' ' '`"
 
-            bootstrappkg="$bootstrappkg $PACKAGE"
-            installed="$installed $nprovides $PACKAGE"
-            nextmissing="$nextmissing $ndep"
-        fi
+        bootstrappkg="$bootstrappkg $PACKAGE"
+        installed="$installed $nprovides $PACKAGE"
+        nextmissing="$nextmissing $ndep"
     done
 
     missing="$nextmissing"
@@ -147,6 +145,8 @@ mkdir -p "$BOOTSTRAPCHROOT/var/cache/pacman/pkg"
 mv "$FETCHDIRPKG"/* "$BOOTSTRAPCHROOT/var/cache/pacman/pkg"
 
 echo "arch" > "$BOOTSTRAPCHROOT/etc/hostname"
+# This is only necessary for reinstall after bootstrapping: signature check
+# is eventually enabled again.
 sed -i 's/^[ \t]*SigLevel[ \t].*/SigLevel = Never/' \
     "$BOOTSTRAPCHROOT/etc/pacman.conf"
 sed -i 's/^[ \t]*Architecture[ \t].*/Architecture = '"$ARCH"'/' \
